name: Push Docker Image to Docker Hub (Latest)

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Deploy Image
        run: |
            docker buildx build --push \
                --tag justinkumpe/incarceration_bot:latest \
                --platform linux/amd64,linux/arm/v7,linux/arm64 .